FROM dockcross/linux-armv7:latest
MAINTAINER Sergey Klimov "sergey.v.klimov@gmail.com"

ENV DEFAULT_DOCKCROSS_IMAGE dockcross/linux-armv7-rust

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH
    
RUN set -eux; \
	mkdir -p $RUSTUP_HOME ; \
	mkdir -p $CARGO_HOME ; \
	chmod -R a+w $RUSTUP_HOME $CARGO_HOME ;
	
RUN set -eux; \
    curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y

RUN set -eux; \
    rustup target add --toolchain nightly armv7-unknown-linux-gnueabihf


# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
